version: "3.9"

services:
  api:
    image: ${API_IMAGE}
    working_dir: /app
    volumes:
      - sqlite_data:/app/db.sqlite3   # persist db.sqlite3 in a named volume
    ports:
      - "8000:8000"
    restart: always

  frontend:
    image: ${FRONTEND_IMAGE}
    ports:
      - "80:80"
    restart: always

volumes:
  sqlite_data:/app/db.sqlite3
