services:
  api:
    image: registry.digitalocean.com/vakaden/api:${IMAGE_TAG:-latest}
    restart: always
    expose:
      - "8000"
    ports:
      - "8000:8000"

  web:
    image: registry.digitalocean.com/vakaden/web:${IMAGE_TAG:-latest}
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api
