version: "3.9"

services:
  frontend:
    image: nginx:1.28-alpine
    container_name: vakaden_frontend
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./frontend/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
    restart: always

  api:
    image: ${API_IMAGE}
    container_name: vakaden_api
    working_dir: /app
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
    expose:
      - "8000"
    restart: always

  certbot:
    image: certbot/certbot
    container_name: vakaden_certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock  # 👈 allow certbot container to talk to Docker
    entrypoint: >
      /bin/sh -c 'trap exit TERM;
      while :;
      do
        certbot renew --webroot -w /var/www/certbot;
        sleep 12h & wait $${!};
      done'
