services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"   # Exposes backend on host port 8000
    volumes:
      - ./backend:/app
    environment:
      - DJANGO_SETTINGS_MODULE=vakaden.settings

