version: "3.9"

volumes:
  sqlite_data:
  
volumes:
  - ./certbot/www:/var/www/certbot
  - ./certbot/conf:/etc/letsencrypt

services:
  api:
    image: ${API_IMAGE}
    working_dir: /app
    volumes:
      - sqlite_data:/app   # persist db.sqlite3 in a named volume
    ports:
      - "8000:8000"
    restart: always

  frontend:
    image: ${FRONTEND_IMAGE}
    ports:
      - "80:80"
    restart: always
