version: "3.8"

services:
  api:
    image: ${API_IMAGE}
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./api.env  # optional if you have API-specific env vars

  frontend:
    image: ${FRONTEND_IMAGE}
    restart: always
    ports:
      - "80:80"
