version: "3.9"

services:
  api:
    image: registry.digitalocean.com/vakaden/api:${TAG}
    restart: always
    expose:
      - "8000"

  web:
    image: registry.digitalocean.com/vakaden/web:${TAG}
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api
