version: '3.9'

services:
  frontend:
    image: registry.digitalocean.com/vakadeni/app:frontend-latest
    container_name: vakaden_frontend
    volumes:
      - ./nginx:/etc/nginx/conf.d 
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
    restart: always

  api:
    image: registry.digitalocean.com/vakadeni/app:api-latest
    container_name: vakaden_api
    volumes:
      # Persist SQLite database in a host folder
      - ./api_data/db.sqlite3:/app/db.sqlite3
    expose:
      - "8000"
    restart: always

  certbot:
    image: certbot/certbot
    container_name: vakaden_certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: >
      /bin/sh -c 'trap exit TERM;
      while :; do
        certbot renew --webroot -w /var/www/certbot;
        sleep 12h & wait $${!};
      done'
