services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        DJANGO_SETTINGS_MODULE: vakaden.settings.production
    restart: always
    expose:
      - "8000"
    ports:
      - "8000:8000"

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api
