# Generated by Django 5.1.1 on 2025-06-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StripeCheckoutSession',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('object_type', models.CharField(default='checkout.session', max_length=50)),
                ('amount_subtotal', models.IntegerField()),
                ('amount_total', models.IntegerField()),
                ('automatic_tax_enabled', models.BooleanField(default=False)),
                ('created', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('currency', models.CharField(max_length=10)),
                ('customer_creation', models.CharField(blank=True, max_length=50, null=True)),
                ('livemode', models.BooleanField(default=False)),
                ('mode', models.CharField(max_length=20)),
                ('payment_method_collection', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_method_types', models.TextField(default='[]')),
                ('payment_status', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('success_url', models.URLField(max_length=1000)),
                ('url', models.URLField(max_length=1000)),
                ('client_reference_id', models.CharField(blank=True, max_length=255, null=True)),
                ('customer', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('invoice', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_intent', models.CharField(blank=True, max_length=255, null=True)),
                ('subscription', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_creation_enabled', models.BooleanField(default=False)),
                ('invoice_creation_data', models.TextField(blank=True, default='{}')),
                ('metadata', models.TextField(blank=True, default='{}')),
            ],
        ),
    ]
