# Generated by Django 3.2.19 on 2025-06-18 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_usersession'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradesmanProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(choices=[('electrician', 'Electrician'), ('plumber', 'Plumber'), ('builder', 'Builder')], max_length=30)),
                ('experience', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=100)),
                ('qualifications', models.FileField(upload_to='qualifications/')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hourly_rate', models.BooleanField(default=True)),
                ('specialties', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tradesman_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
