# Generated by Django 3.2.19 on 2025-06-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tradesmanprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradesmanprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
