name: Build and Push Images

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: registry.digitalocean.com/vakaden
  APP_IMAGE_NAME: app  # Single repository for both API & frontend

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Login to DigitalOcean Container Registry
        run: doctl registry login

      - name: Get short commit SHA
        run: echo "SHORT_SHA=$(echo $GITHUB_SHA | head -c7)" >> $GITHUB_ENV

      - name: Build API image
        run: docker build -t $REGISTRY/$APP_IMAGE_NAME:api-${SHORT_SHA} -f ./api/Dockerfile ./api

      - name: Build Frontend image
        run: docker build -t $REGISTRY/$APP_IMAGE_NAME:frontend-${SHORT_SHA} -f ./frontend/Dockerfile ./frontend

      - name: Push API image
        run: docker push $REGISTRY/$APP_IMAGE_NAME:api-${SHORT_SHA}

      - name: Push Frontend image
        run: docker push $REGISTRY/$APP_IMAGE_NAME:frontend-${SHORT_SHA}
