name: CI and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version (e.g. v1.0.3)'
        required: true

env:
  REGISTRY: registry.digitalocean.com/vakaden
  API_IMAGE_NAME: api
  WEB_IMAGE_NAME: web

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build API image
        run: docker build -t $REGISTRY/$API_IMAGE_NAME:latest -f ./api/Dockerfile ./api

      - name: Build Web image
        run: docker build -t $REGISTRY/$WEB_IMAGE_NAME:latest -f ./web/Dockerfile ./web

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Login to registry
        run: doctl registry login

      - name: Push API image
        run: docker push $REGISTRY/$API_IMAGE_NAME:${{ github.event.inputs.version }}

      - name: Push Web image
        run: docker push $REGISTRY/$WEB_IMAGE_NAME:${{ github.event.inputs.version }}

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on droplet via SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd ~/app-directory
            # Export the version so the compose file can use it
            export APP_VERSION=${{ github.event.inputs.version }}

            # Pull the updated images
            docker compose -f docker-compose.prod.yml pull

            # Recreate containers with new images, remove old containers
            docker compose -f docker-compose.prod.yml up -d --remove-orphans
