name: Build and Push API + Frontend

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: "vakaden"
  IMAGE_NAME: "app"  # Your container name

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry
        run: doctl registry login --expiry-seconds 600
      
      - name: Delete all tags and manifests
        run: |
          # Get all tags including "none"
          TAGS=$(doctl registry repository list-tags vakaden/app --format "{{.Tag}}" --no-header)
          if [ -n "$TAGS" ]; then
            echo "Found tags:"
            echo "$TAGS"
            
            # Convert newline-separated list to space-separated
            TAGS=$(echo "$TAGS" | tr '\n' ' ')
            
            # Delete each tag, including "none"
            for tag in $TAGS; do
              if [ -n "$tag" ]; then
                echo "Deleting tag $tag"
                doctl registry repository delete-tag vakaden/app $tag -f
              fi
            done
          else
            echo "No tags found"
          fi

          # Then delete all remaining manifests
          MANIFESTS=$(doctl registry repository list-manifests vakaden/app --format "{{.Digest}}" --no-header)
          if [ -n "$MANIFESTS" ]; then
            echo "Found remaining manifests:"
            echo "$MANIFESTS"
            
            # Convert newline-separated list to space-separated
            MANIFESTS=$(echo "$MANIFESTS" | tr '\n' ' ')
            
            # Delete each manifest
            for digest in $MANIFESTS; do
              if [ -n "$digest" ] && [ "$digest" != "<nil>" ]; then
                echo "Deleting remaining manifest $digest"
                doctl registry repository delete-manifest vakaden/app $digest -f
              fi
            done
          else
            echo "No remaining manifests found"
          fi

      - name: Garbage collect repository
        run: doctl registry garbage-collection start -f ${{ env.REGISTRY }}

      - name: Build and push API image
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}-api
          docker build -t ${{ env.REGISTRY }}/app:$IMAGE_TAG-api -f ./api/Dockerfile ./api
          docker push ${{ env.REGISTRY }}/app:$IMAGE_TAG-api

      - name: Build and push Frontend image
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}-frontend
          docker build -t ${{ env.REGISTRY }}/app:$IMAGE_TAG -f ./frontend/Dockerfile ./frontend
          docker push ${{ env.REGISTRY }}/app:$IMAGE_TAG
