name: Build and Push API + Frontend

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: "vakaden"
  IMAGE_NAME: "app"  # Your container name

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry
        run: doctl registry login --expiry-seconds 600

      - name: Delete old images
        run: |
           for digest in $(doctl registry repository list-manifests ${{ env.REGISTRY }} --format Digest --no-header); do
            if [ -n "$digest" ] && [ "$digest" != "<nil>" ]; then
              echo "Deleting ${{ env.REGISTRY }}@$digest"
              doctl registry repository delete-manifest ${{ env.REGISTRY }} $digest -f
            else
              echo "Skipping empty digest"
            fi
           done

      #- name: Garbage collect repository
      #  run: doctl registry garbage-collection start --include-untagged-manifests --force ${{ env.REGISTRY }}
