name: Build and Push API + Frontend

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: "vakaden"
  REPO: "app"
  IMAGE_NAME: "app"  # Your container name

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry
        run: doctl registry login --expiry-seconds 600

      - name: Remove all old images
        run: if [ ! -z "$(doctl registry repository list | grep "$(echo $REGISTRY)")" ]; then doctl registry repository delete-manifest $(echo $REGISTRY) $(doctl registry repository list-tags $(echo $REGISTRY) | grep -o "sha.*") --force; else echo "No repository"; fi
    
