jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and push frontend
        run: |
          FRONTEND_TAG="frontend-latest"
          docker build -t registry.digitalocean.com/vakaden/app:$FRONTEND_TAG ./frontend
          docker push registry.digitalocean.com/vakaden/app:$FRONTEND_TAG
          echo "frontend-tag=$FRONTEND_TAG" >> $GITHUB_OUTPUT

      - name: Build and push API
        run: |
          API_TAG="api-latest"
          docker build -t registry.digitalocean.com/vakaden/app:$API_TAG ./api
          docker push registry.digitalocean.com/vakaden/app:$API_TAG
          echo "api-tag=$API_TAG" >> $GITHUB_OUTPUT
