name: Build-and-Push

on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    
      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600

      - name: Build and push frontend
        run: |
          FRONTEND_TAG="frontend-latest"
          docker build -t registry.digitalocean.com/vakadeni/app:$FRONTEND_TAG ./frontend
          docker push registry.digitalocean.com/vakadeni/app:$FRONTEND_TAG
          echo "frontend-tag=$FRONTEND_TAG" >> $GITHUB_OUTPUT

      - name: Build and push API
        run: |
          API_TAG="api-latest"
          docker build -t registry.digitalocean.com/vakadeni/app:$API_TAG ./api
          docker push registry.digitalocean.com/vakadeni/app:$API_TAG
          echo "api-tag=$API_TAG" >> $GITHUB_OUTPUT


