name: Build and Push API + Frontend

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: "vakaden"
  REPO: "app"
  IMAGE_NAME: "app"  # Your container name

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry
        run: doctl registry login --expiry-seconds 600

      - name: Delete all images from repository
        run: |
          REPO="${{ env.REPO }}"
          REGISTRY="${{ env.REGISTRY }}"

          echo "Fetching tags for $REPO in registry $REGISTRY..."
          TAGS=$(doctl registry repository list-tags $REPO $REGISTRY --format Tag --no-header)

          if [ -z "$TAGS" ]; then
            echo "No tags found in $REPO"
          else
            for tag in $TAGS; do
              echo "Deleting tag $tag"
              doctl registry repository delete-tag $REPO $tag --registry $REGISTRY -f
            done
          fi

          echo "Starting garbage collection..."
          doctl registry garbage-collection start --include-untagged-manifests --force $REGISTRY
