name: Deploy

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [ "main" ]
    tags: [ "v*" ]     # Also trigger on version tags

jobs:
  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on droplet via SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          script: |
            REGISTRY=${{ env.REGISTRY }}
            APP_IMAGE_NAME=${{ env.APP_IMAGE_NAME }}
            VERSION=$(echo $GITHUB_SHA | head -c7)

            cd ~/vakaden

            # Update environment file for docker-compose
            echo "API_IMAGE=$REGISTRY/$APP_IMAGE_NAME:api-$VERSION" > .env
            echo "FRONTEND_IMAGE=$REGISTRY/$APP_IMAGE_NAME:frontend-$VERSION" >> .env

            docker-compose -f docker-compose.prod.yml pull
            docker-compose -f docker-compose.prod.yml run --rm api python manage.py migrate
            docker-compose -f docker-compose.prod.yml up -d --remove-orphans --timeout 30

            echo "Deployed successfully"
