name: Deploy

on:
  workflow_run:
    workflows: ["Build and Push Images"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: false

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on droplet via SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          script: |
            set -e

            REGISTRY=registry.digitalocean.com/vakaden
            APP_IMAGE_NAME=app
            VERSION=${{ github.event.workflow_run.head_sha || github.sha }}
            VERSION=$(echo $VERSION | head -c7)

            cd ~/vakaden

            echo "API_IMAGE=$REGISTRY/$APP_IMAGE_NAME:api-$VERSION" > .env
            echo "FRONTEND_IMAGE=$REGISTRY/$APP_IMAGE_NAME:frontend-$VERSION" >> .env

            echo "== Pulling latest images =="
            docker-compose -f docker-compose.prod.yml pull

            echo "== Applying Django migrations (if any) =="
            docker-compose -f docker-compose.prod.yml run --rm api python manage.py migrate --noinput || true

            echo "== Starting containers in detached mode =="
            docker-compose -f docker-compose.prod.yml up -d --remove-orphans

            echo "== Deployment complete =="
            exit 0
