name: Deploy to Droplet

on:
  workflow_dispatch:
  push:
    branches:
      - main   # or your deploy branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH }}

      - name: Deploy on Droplet
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
            cd /home/${{ secrets.USERNAME }}/vakaden  # path to your project
            docker login registry.digitalocean.com -u doctl --password-stdin <<< "${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}"
            docker compose pull
            docker compose up -d --remove-orphans
            docker system prune -af
          EOF
