name: Deploy

on:
  workflow_run:
    workflows: ["Build-and-Push"]
    types:
      - completed

env:
  REGISTRY: registry.digitalocean.com/vakaden
  APP_IMAGE_NAME: app

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get build version from triggering workflow
        id: get_version
        run: echo "version=$(echo ${{ github.event.workflow_run.head_sha }} | head -c7)" >> $GITHUB_OUTPUT

      - name: Copy docker-compose file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          source: "docker-compose.prod.yml"
          target: "~/vakaden/docker-compose.prod.yml"

      - name: Deploy on droplet via SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          script: |
            REGISTRY=${{ env.REGISTRY }}
            APP_IMAGE_NAME=${{ env.APP_IMAGE_NAME }}
            VERSION=${{ steps.get_version.outputs.version }}

            cd ~/vakaden

            # Update .env for docker-compose
            echo "API_IMAGE=$REGISTRY/$APP_IMAGE_NAME:api-$VERSION" > .env
            echo "FRONTEND_IMAGE=$REGISTRY/$APP_IMAGE_NAME:frontend-$VERSION" >> .env

            docker compose --env-file .env -p vakaden -f docker-compose.prod.yml pull --no-parallel --quiet
            docker compose --env-file .env -p vakaden -f docker-compose.prod.yml up -d --remove-orphans

            echo "✅ Deployed version $VERSION"
