name: Deploy

on:
  workflow_run:
    workflows: ["Build-and-Push"]
    types:
      - completed

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSHKEY }}

      - name: Deploy on Droplet
        run: |
          ssh -o StrictHostKeyChecking=no \
            FRONTEND_TAG=${{ github.event.workflow_run.outputs.frontend-tag }} \
            API_TAG=${{ github.event.workflow_run.outputs.api-tag }} \
            ${{ secrets.USERNAME }}@${{ secrets.HOST }} "
              cd ~/vakaden || exit 1
              docker-compose -f docker-compose.prod.yml pull
              docker-compose -f docker-compose.prod.yml up -d --remove-orphans
              docker system prune -af
            "